# Site settings
title: Finance Hub
description: Your Guide to Money Success in Pidgin
baseurl: ""
url: "https://smartfinancehub.github.io"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: all
  endings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
